import "@/styles/globals.css";
import getTheme from "@/config/theme";
import { ThemeProvider } from "@mui/material";
import { QueryClientProvider } from "@tanstack/react-query";
import Head from "next/head";
import { SidebarProvider } from "@/contexts/SidebarContext";
import queryClient from "@/config/queryClient";
import { LocalizationProvider } from "@mui/x-date-pickers";
import { AdapterDayjs } from "@mui/x-date-pickers/AdapterDayjs";
import { AuthProvider } from "@/contexts/AuthContext";
import { SessionProvider } from "next-auth/react";

export default function App({
  Component,
  pageProps: { session, ...pageProps },
}) {
  return (
    <SessionProvider session={session}>
      <QueryClientProvider client={queryClient}>
        <AuthProvider>
          <ThemeProvider theme={getTheme()}>
            <LocalizationProvider
              dateAdapter={AdapterDayjs}
              adapterLocale="pt-br"
            >
              <SidebarProvider>
                <Head>
                  <title>Controle de estoque</title>
                  <meta
                    name="description"
                    content="Generated by create next app"
                  />
                  <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                  />
                  <link rel="icon" href="/favicon.ico" />
                </Head>
                <Component {...pageProps} />
              </SidebarProvider>
            </LocalizationProvider>
          </ThemeProvider>
        </AuthProvider>
      </QueryClientProvider>
    </SessionProvider>
  );
}
