# Generated by Django 5.1.1 on 2024-10-05 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lanchonete', '0003_estoque'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='quantidade_estoque',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
