# Generated by Django 5.1.1 on 2024-10-19 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lanchonete', '0006_alter_produto_quantidade_estoque_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='data_validade',
            field=models.DateField(),
        ),
    ]
