# Generated by Django 5.1.1 on 2024-10-26 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lanchonete', '0008_rename_endereco_fornecedor_complemento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fornecedor',
            name='cnpj',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
